/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Wed Sep 09 10:39:31 2015. */

#include "dragonfly_fcb_cli.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ReceiverSignalValues_fields[7] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, ReceiverSignalValues, throttle, throttle, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValues, aileron, throttle, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValues, elevator, aileron, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValues, rudder, elevator, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValues, gear, rudder, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValues, aux1, gear, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorSignalValues_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, MotorSignalValues, M1, M1, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, MotorSignalValues, M2, M1, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, MotorSignalValues, M3, M2, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, MotorSignalValues, M4, M3, 0),
    PB_LAST_FIELD
};

const pb_field_t SensorSamples_fields[10] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SensorSamples, gyroAngRateXb, gyroAngRateXb, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, gyroAngRateYb, gyroAngRateXb, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, gyroAngRateZb, gyroAngRateYb, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, accX, gyroAngRateZb, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, accY, accX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, accZ, accY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, magX, accZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, magY, magX, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, magZ, magY, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightStates_fields[13] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, FlightStates, posX, posX, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, posY, posX, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, posZ, posY, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, velX, posZ, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, velY, velX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, velZ, velY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, angRoll, velZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, angPitch, angRoll, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, angYaw, angPitch, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, rateRoll, angYaw, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, ratePitch, rateRoll, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStates, rateYaw, ratePitch, 0),
    PB_LAST_FIELD
};

const pb_field_t PIDControlParams_fields[13] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, PIDControlParams, K_vxy, K_vxy, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Ti_vxy, K_vxy, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Td_vxy, Ti_vxy, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, K_vz, Td_vxy, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Ti_vz, K_vz, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Td_vz, Ti_vz, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, K_rollpitch, Td_vz, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Ti_rollpitch, K_rollpitch, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Td_rollpitch, Ti_rollpitch, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, K_yawrate, Td_rollpitch, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Ti_yawrate, K_yawrate, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParams, Td_yawrate, Ti_yawrate, 0),
    PB_LAST_FIELD
};

const pb_field_t ControlReferenceSignals_fields[8] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, ControlReferenceSignals, refVx, refVx, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignals, refVy, refVx, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignals, refVz, refVy, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignals, refRoll, refVz, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignals, refPitch, refRoll, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignals, refYaw, refPitch, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignals, refYawRate, refYaw, 0),
    PB_LAST_FIELD
};

const pb_field_t SimulatedStates_fields[13] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SimulatedStates, posX, posX, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, posY, posX, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, posZ, posY, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, velX, posZ, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, velY, velX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, velZ, velY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, angRoll, velZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, angPitch, angRoll, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, angYaw, angPitch, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, rateRoll, angYaw, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, ratePitch, rateRoll, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStates, rateYaw, ratePitch, 0),
    PB_LAST_FIELD
};


