/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Mon May 18 17:55:03 2015. */

#include "fcb-fsm.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ConnectToFsm_fields[2] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, ConnectToFsm, fcn, fcn, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightSensorSamples_fields[10] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, FlightSensorSamples, gyroRoll, gyroRoll, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, gyroPitch, gyroRoll, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, gyroYaw, gyroPitch, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, accX, gyroYaw, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, accY, accX, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, accZ, accY, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, magX, accZ, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, magY, magX, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, FlightSensorSamples, magZ, magY, 0),
    PB_LAST_FIELD
};

const pb_field_t ProximitySensorSamples_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, ProximitySensorSamples, posX, posX, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, ProximitySensorSamples, negX, posX, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, ProximitySensorSamples, posY, negX, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, ProximitySensorSamples, negY, posY, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, ProximitySensorSamples, posZ, negY, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, ProximitySensorSamples, negZ, posZ, 0),
    PB_LAST_FIELD
};

const pb_field_t QuadcopterConfig_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, QuadcopterConfig, Mass, Mass, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, QuadcopterConfig, Ixx, Mass, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, QuadcopterConfig, Iyy, Ixx, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, QuadcopterConfig, Izz, Iyy, 0),
    PB_LAST_FIELD
};

const pb_field_t RCConfig_fields[13] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, RCConfig, throttleMinMicroS, throttleMinMicroS, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, throttleMaxMicroS, throttleMinMicroS, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, aileronMinMicroS, throttleMaxMicroS, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, aileronMaxMicroS, aileronMinMicroS, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, elevatorMinMicroS, aileronMaxMicroS, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, elevatorMaxMicroS, elevatorMinMicroS, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, rudderMinMicroS, elevatorMaxMicroS, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, rudderMaxMicroS, rudderMinMicroS, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, gearOnMicroS, rudderMaxMicroS, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, gearOffMicroS, gearOnMicroS, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, auxOnMicroS, gearOffMicroS, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, auxOffMicroS, auxOnMicroS, 0),
    PB_LAST_FIELD
};

const pb_field_t RCSamples_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, RCSamples, throttleMicroS, throttleMicroS, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, aileronMicroS, throttleMicroS, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, elevatorMicroS, aileronMicroS, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, rudderMicroS, elevatorMicroS, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, gearMicroS, rudderMicroS, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, auxMicroS, gearMicroS, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorSamples_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, MotorSamples, Motor1NanoS, Motor1NanoS, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, MotorSamples, Motor2NanoS, Motor1NanoS, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, MotorSamples, Motor3NanoS, Motor2NanoS, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, MotorSamples, Motor4NanoS, Motor3NanoS, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightControlSystemParameters_fields[10] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, FlightControlSystemParameters, AltitudeCtrl_K, AltitudeCtrl_K, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, AltitudeCtrl_Ti, AltitudeCtrl_K, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, AltitudeCtrl_Td, AltitudeCtrl_Ti, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, RollPitchCtrl_K, AltitudeCtrl_Td, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, RollPitchCtrl_Ti, RollPitchCtrl_K, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, RollPitchCtrl_Td, RollPitchCtrl_Ti, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, YawCtrl_K, RollPitchCtrl_Td, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, YawCtrl_Ti, YawCtrl_K, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, FlightControlSystemParameters, YawCtrl_Td, YawCtrl_Ti, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightCommands_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, FlightCommands, Climb, Climb, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, FlightCommands, Descend, Climb, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, FlightCommands, RotateClockwise, Descend, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, FlightCommands, RotateAnticlockwise, RotateClockwise, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, FlightCommands, SidewaysToPort, RotateAnticlockwise, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, FlightCommands, SidewaysToStarboard, SidewaysToPort, 0),
    PB_LAST_FIELD
};

const pb_field_t CurrentFlightCmdSource_fields[2] = {
    PB_FIELD(  1, ENUM    , REQUIRED, STATIC  , FIRST, CurrentFlightCmdSource, source, source, 0),
    PB_LAST_FIELD
};


