/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Tue Mar 08 09:33:23 2016. */

#include "dragonfly_fcb.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t ReceiverSignalValuesProto_fields[8] = {
    PB_FIELD(  1, BOOL    , OPTIONAL, STATIC  , FIRST, ReceiverSignalValuesProto, is_active, is_active, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValuesProto, throttle, is_active, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValuesProto, aileron, throttle, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValuesProto, elevator, aileron, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValuesProto, rudder, elevator, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValuesProto, gear, rudder, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, ReceiverSignalValuesProto, aux1, gear, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorSignalValuesProto_fields[5] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, MotorSignalValuesProto, M1, M1, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, MotorSignalValuesProto, M2, M1, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, MotorSignalValuesProto, M3, M2, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, MotorSignalValuesProto, M4, M3, 0),
    PB_LAST_FIELD
};

const pb_field_t SensorSamplesProto_fields[10] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SensorSamplesProto, gyroAngRateXb, gyroAngRateXb, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, gyroAngRateYb, gyroAngRateXb, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, gyroAngRateZb, gyroAngRateYb, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, accX, gyroAngRateZb, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, accY, accX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, accZ, accY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, magX, accZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, magY, magX, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamplesProto, magZ, magY, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightStatesProto_fields[13] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, FlightStatesProto, posX, posX, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, posY, posX, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, posZ, posY, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, velX, posZ, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, velY, velX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, velZ, velY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, rollAngle, velZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, pitchAngle, rollAngle, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, yawAngle, pitchAngle, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, rollRate, yawAngle, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, pitchRate, rollRate, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightStatesProto, yawRate, pitchRate, 0),
    PB_LAST_FIELD
};

const pb_field_t PIDControlParamsProto_fields[13] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, PIDControlParamsProto, K_vxy, K_vxy, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Ti_vxy, K_vxy, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Td_vxy, Ti_vxy, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, K_vz, Td_vxy, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Ti_vz, K_vz, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Td_vz, Ti_vz, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, K_rollpitch, Td_vz, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Ti_rollpitch, K_rollpitch, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Td_rollpitch, Ti_rollpitch, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, K_yawrate, Td_rollpitch, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Ti_yawrate, K_yawrate, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, PIDControlParamsProto, Td_yawrate, Ti_yawrate, 0),
    PB_LAST_FIELD
};

const pb_field_t ControlReferenceSignalsProto_fields[8] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, ControlReferenceSignalsProto, refVx, refVx, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignalsProto, refVy, refVx, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignalsProto, refVz, refVy, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignalsProto, refRoll, refVz, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignalsProto, refPitch, refRoll, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignalsProto, refYaw, refPitch, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, ControlReferenceSignalsProto, refYawRate, refYaw, 0),
    PB_LAST_FIELD
};

const pb_field_t SimulatedStatesProto_fields[13] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SimulatedStatesProto, posX, posX, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, posY, posX, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, posZ, posY, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, velX, posZ, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, velY, velX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, velZ, velY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, angRoll, velZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, angPitch, angRoll, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, angYaw, angPitch, 0),
    PB_FIELD( 10, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, rateRoll, angYaw, 0),
    PB_FIELD( 11, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, ratePitch, rateRoll, 0),
    PB_FIELD( 12, FLOAT   , OPTIONAL, STATIC  , OTHER, SimulatedStatesProto, rateYaw, ratePitch, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
