/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.3 at Mon May 11 16:40:27 2015. */

#include "fcb-fsm.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SensorSamples_fields[10] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, SensorSamples, gyroRoll, gyroRoll, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, gyroPitch, gyroRoll, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, gyroYaw, gyroPitch, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, accX, gyroYaw, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, accY, accX, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, accZ, accY, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, magX, accZ, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, magY, magX, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, SensorSamples, magZ, magY, 0),
    PB_LAST_FIELD
};

const pb_field_t QuadcopterConfig_fields[5] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, QuadcopterConfig, Mass, Mass, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, QuadcopterConfig, Ixx, Mass, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, QuadcopterConfig, Iyy, Ixx, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, QuadcopterConfig, Izz, Iyy, 0),
    PB_LAST_FIELD
};

const pb_field_t RCConfig_fields[13] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, RCConfig, throttleMinMicros, throttleMinMicros, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, throttleMaxMicros, throttleMinMicros, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, aileronMinMicros, throttleMaxMicros, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, aileronMaxMicros, aileronMinMicros, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, elevatorMinMicros, aileronMaxMicros, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, elevatorMaxMicros, elevatorMinMicros, 0),
    PB_FIELD(  7, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, rudderMinMicros, elevatorMaxMicros, 0),
    PB_FIELD(  8, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, rudderMaxMicros, rudderMinMicros, 0),
    PB_FIELD(  9, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, gearOnMicros, rudderMaxMicros, 0),
    PB_FIELD( 10, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, gearOffMicros, gearOnMicros, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, auxOnMicros, gearOffMicros, 0),
    PB_FIELD( 12, UINT32  , OPTIONAL, STATIC  , OTHER, RCConfig, auxOffMicros, auxOnMicros, 0),
    PB_LAST_FIELD
};

const pb_field_t RCSamples_fields[7] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, RCSamples, throttleMicros, throttleMicros, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, aileronMicros, throttleMicros, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, elevatorMicros, aileronMicros, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, rudderMicros, elevatorMicros, 0),
    PB_FIELD(  5, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, gearMicros, rudderMicros, 0),
    PB_FIELD(  6, UINT32  , OPTIONAL, STATIC  , OTHER, RCSamples, auxMicros, gearMicros, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorSamples_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, MotorSamples, Motor1Nanos, Motor1Nanos, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, MotorSamples, Motor2Nanos, Motor1Nanos, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, MotorSamples, Motor3Nanos, Motor2Nanos, 0),
    PB_FIELD(  4, UINT32  , OPTIONAL, STATIC  , OTHER, MotorSamples, Motor4Nanos, Motor3Nanos, 0),
    PB_LAST_FIELD
};

const pb_field_t FlightControl_fields[10] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, FlightControl, AltitudeCtrl_K, AltitudeCtrl_K, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, AltitudeCtrl_Ti, AltitudeCtrl_K, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, AltitudeCtrl_Td, AltitudeCtrl_Ti, 0),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, RollPitchCtrl_K, AltitudeCtrl_Td, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, RollPitchCtrl_Ti, RollPitchCtrl_K, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, RollPitchCtrl_Td, RollPitchCtrl_Ti, 0),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, YawCtrl_K, RollPitchCtrl_Td, 0),
    PB_FIELD(  8, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, YawCtrl_Ti, YawCtrl_K, 0),
    PB_FIELD(  9, FLOAT   , OPTIONAL, STATIC  , OTHER, FlightControl, YawCtrl_Td, YawCtrl_Ti, 0),
    PB_LAST_FIELD
};


